#!/bin/bash

if [ ! -e cm_script ]
then
 echo Run From ~/scripts.
fi

while :
do

  clear

  echo    Amount Of Processors = $JOB
  echo    Network Strength = $REPO
  echo    Device Name = $DEVICE

  echo "  1 - Options for CM9"
  echo "  2 - Options for CM10"
  echo "  3 - Options for AOKP JB"
  echo "  4 - Options for AOKP ICS"
  echo "  5 - Set Device"
  echo "  6 - Set number of processors"
  echo "  7 - Install Necessary packages"
  echo "  8 - Set internet connection qualitly"
  echo "  u - Update Sport's Script"
  echo "  x - Exit"
  echo
  echo 
  echo -n "Enter option: "
  read opt
  
  if [ "$?" != "1" ]
  then
    case $opt in
      1) ~/scripts/cm9;;
      2) ~/scripts/cm10;;
      3) ~/scripts/aokp_jb;;
      4) ~/scripts/aokp_ics;;
      5) ~/scripts/device;;
      6) ~/scripts/processor;;
      7) mkdir -p ~/bin; curl https://dl-ssl.google.com/dl/googlesource/git-repo/repo > ~/bin/repo; sudo cp ~/bin/repo /usr/bin && sudo chmod a+x /usr/bin/repo; sudo apt-get update && sudo apt-get install git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev libc6-dev lib32ncurses5-dev ia32-libs x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev g++-multilib mingw32 tofrodos python-markdown libxml2-utils xsltproc; sudo add-apt-repository "deb http://archive.canonical.com/ lucid partner" && sudo apt-get update && sudo apt-get install sun-java6-jdk;;
      8) ~/scripts/repo;;
      u) cd ~/scripts && git pull;;
      x) exit;;
    esac
  fi

done
