#!/bin/bash

while :
do

  clear

  echo "  1 - Sport's CM9 for Ruby"
  echo "  2 - Sport's CM10 for Ruby"
  echo "  3 - CM9 Source"
  echo "  4 - CM10 Source"
  echo "  5 - AOKP JB Source"
  echo "  6 - Update Sport's CM9 tree"
  echo "  6 - Update Sport's CM10 tree"
  echo "  x - Go back"
  echo
  echo 
  echo -n "Enter option: "
  read opt
  
  if [ "$?" != "1" ]
  then
    case $opt in
      1) cd ~/ics/device && mkdir htc && cd htc; git clone git://github.com/CM-Ruby/android_device_htc_ruby.git -b ics ruby; cd ~/ics/vendor && mkdir htc && cd htc && git clone git://github.com/CM-Ruby/proprietary_vendor_htc_ruby.git -b ics ruby; cd ~/scripts;;
      2) cd ~/cm10/device && mkdir htc && cd htc; git clone git://github.com/CM-Ruby/android_device_htc_ruby.git -b jellybean ruby; cd ~/cm10/vendor && mkdir htc && cd htc && git clone git://github.com/CM-Ruby/proprietary_vendor_htc_ruby.git -b jellybean ruby; cd ~/scripts;;
      3) cd ~/ && mkdir ics; cd ~/ics; repo init -u git://github.com/CyanogenMod/android.git -b ics; repo sync -j$REPO;;
      4) cd ~/ && mkdir cm10; cd ~/cm10; repo init -u git://github.com/CyanogenMod/android.git -b jellybean; repo sync -j$REPO;;
      5) cd ~/ && mkdir AOKP && cd ~/AOKP && repo init -u https://github.com/AOKP/platform_manifest.git -b jb && repo sync -j$REPO;;
      6) cd ~/ics/device/htc/ruby && git pull; cd ~/ics/vendor/htc/ruby && git pull; cd ~/scripts;;
      7) cd ~/cm10/device/htc/ruby && git pull; cd ~/cm10/vendor/htc/ruby && git pull; cd ~/scripts;;
      x) ~/scripts/cm_script;;
    esac
  fi

done
